version: '3'

includes:
  dc:
    taskfile: .devcontainer/Taskfile.yml
    dir: .devcontainer

tasks:
  checkpoint:
    dir: scripts
    cmds:
      - npx zx checkpoint.mjs

  download:
    dir: mainrun
    cmds:
      - python3 download_dataset.py

  train:
    deps: [checkpoint, download]
    dir: mainrun
    cmds:
      - python3 train.py

  train_nohup:
    dir: mainrun
    cmds:
      - nohup python3 train.py sweep > train.log 2>train.err &

  submit:
    deps: [checkpoint]
    dir: scripts
    cmds:
      - npx zx submit.mjs
    